import product1 from "../assets/productImage1.png";
import product2 from "../assets/productImage2.png";
import product3 from "../assets/productImage3.png";
import product4 from "../assets/productImage4.png";

export const products = [
  {
    productId: 1,
    image: product1,
    alt: "handle omnires",
    discount: 30,
    name: "Connection with a handle Omnires round",
    price: 45.0,
    oldPrice: 55.0,
    description: "Omnires | Part No. 2123532",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: true,
    category: "Home ",
  },
  {
    productId: 2,
    image: product2,
    alt: "image2",
    discount: 30,
    name: "Countertop washbasin GoodHome Tekapo",
    price: 51.0,
    oldPrice: 64.0,
    description: "Omnires | Part No. 2123532",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: true,
    category: " Garden",
  },

  {
    productId: 3,
    image: product3,
    alt: "image3",
    discount: 30,
    name: "Perforated Simpson tape 25 x 2500 x 2 mm",
    price: 51.0,
    oldPrice: 64.0,
    description: "GoodHome | Part No. 234565",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: true,
    category: "Motors",
  },
  {
    productId: 4,
    image: product4,
    alt: "image4",
    discount: 30,
    name: "AMBER DECOR Bulb 60W, E27 590",
    price: 51.0,
    oldPrice: 64.0,
    description: "GoodHome | Part No. 234565",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: false,
    category: "Electronics",
  },
  {
    productId: 5,
    image: product1,
    alt: "handle omnires",
    discount: 30,
    name: "Connection with a handle Omnires round part 2",
    price: 45.0,
    oldPrice: 55.0,
    description: "Omnires | Part No. 2123532",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: true,
    category: "Home",
  },
  {
    productId: 6,
    image: product2,
    alt: "image2",
    discount: 30,
    name: "Countertop washbasin GoodHome Tekapo part 2",
    price: 51.0,
    oldPrice: 64.0,
    description: "Omnires | Part No. 2123532",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: true,
    category: "Garden",
  },

  {
    productId: 7,
    image: product3,
    alt: "image3",
    discount: 30,
    name: "Perforated Simpson tape 25 x 2500 x 2 mm part 2",
    price: 51.0,
    oldPrice: 64.0,
    description: "GoodHome | Part No. 234565",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: true,
    category: "Motors",
  },
  {
    productId: 8,
    image: product4,
    alt: "image4",
    discount: 30,
    name: "AMBER DECOR Bulb 60W, E27 590 part 2",
    price: 51.0,
    oldPrice: 64.0,
    description: "GoodHome | Part No. 234565",
    description1: "Basin width: 45cm, Basin Height: 12 cm, Basin depth:35cm",
    stock: false,
    category: "Electronics",
  },
];
